export default [
    { label: "Caribbean", value: "Caribbean" },
    { label: "Demoted to SL", value: "Demoted to SL" },
    { label: "Extended", value: "Extended" },
    { label: "International Budget", value: "International Budget" },
    { label: "International New", value: "International New" },
    { label: "International Old", value: "International Old" },
    { label: "International Omit", value: "International Omit" },
    { label: "International Possible", value: "International Possible" },
    { label: "Never", value: "Never" },
    { label: "New", value: "New" },
    { label: "New Shortlisted", value: "New Shortlisted" },
    { label: "Next Year", value: "Next Year" },
    { label: "Next Year-Omit", value: "Next Year-Omit" },
    { label: "Next Year-SL", value: "Next Year-SL" },
    { label: "Next Year-SL/Omit", value: "Next Year-SL/Omit" },
    { label: "Next Year-Upgraded", value: "Next Year-Upgraded" },
    { label: "Old", value: "old" },
    { label: "Omitted", value: "Omitted" },
    { label: "Possible", value: "Possible" },
    { label: "Shortlisted", value: "Shortlisted" },
    { label: "Upgraded", value: "Upgraded" },
    { label: "USA", value: "USA" },
]